config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :barracks
  resources :users

  root "barracks#index"

end

app/models/barrack.rb
class Barrack < ActiveRecord::Base

  has_many :reservations
  has_many :users
  # validates :user, presence: true

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user

  def create
    reservation = Reservation.new(reservation_params)
    reservation.save
  end

  private

  def reservation_params
    params.require(:reservation).permit(:user_id, :breakfast, :breakfast_choice, :lunch, :lunch_choice, :dinner, :dinner_choice)
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :reservations

  belongs_to :barrack
  accepts_nested_attributes_for :barrack


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    user.name = auth.info.name   # assuming the user model has a name
    user.image = auth.info.image # assuming the user model has an image
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
            devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:surname, :email, :password, :current_password, :is_mess_staff, :rank) }
        end
end

app/controllers/barracks_controller.rb
class BarracksController < ApplicationController

  def index
    @barracks = Barrack.all
  end

  def new
    @barrack = Barrack.new
  end

  def create
    Barrack.create(barrack_params)
    redirect_to '/barracks'
  end

  def show
    @barrack = Barrack.find(params[:id])
  end

  private

  def barrack_params
    params.require(:barrack).permit(:name)
  end


end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @barracks = Barrack.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/barracks_helper.rb
module BarracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/barracks/index.html.erb
<% if @barracks.any? %>
  <% @barracks.each do |barrack| %>
    <h2> <%= link_to barrack.name, barrack_path(barrack) %> </h2>
  <% end %>
<% else %>
  No messes yet
<% end %>

<%= link_to "Add a mess", new_barrack_path %>

app/views/barracks/new.html.erb
<%= form_for @barrack do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit "Create mess"%>
<% end %>

app/views/barracks/show.html.erb
<p><%= @barrack.name %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Barracks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header class="navbar navbar-fixed-top">
    <div class="container">
      <%= link_to image_tag("logo_75.png"), '/', id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home",   '#' %></li>
          <% if user_signed_in? %>
          <li><%= link_to "My Account", edit_user_registration_path %></li>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>
  <div class="container">
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>

</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h1> <%= @user.email %> </h1>